### ISSUE TITLE
Bot broken

### ISSUE THREAD

**Issue by karx** [karx/twitter-kClips#22]
Need to investigate

```
You will see this message every second
(node:11680) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at getRandomClipFromTwitch (D:\src\twitter-kClips\twitch-clips.js:84:47)
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at async post_a_tweet (D:\src\twitter-kClips\index.js:17:25)
```

**Comment by karx** [comment]
Did not update the new twitch secret on server. Want to know if old secrets expire or still remain in use.

**Comment by karx** [comment]
This issue was me being lazy while initially lazy while building this. Should have used Auth service  properly, however twitch allowed to use Twitch app secret directly in Requests for authorization.
